ggg = 
CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98
1
SRC =
OBJ =$(SRC:.cpp=.o)

H =
all :$(ggg)

$(ggg):$(OBJ) $(H)
		$(CC) $(CFLAGS) $(OBJ) -o $(ggg) -fsanitize=address -g3

clean : 
		rm -f $(OBJ)

fclean : clean
	rm -f $(ggg)
re : fclean all


vinsmok: all  clean
		@clear
